### ISSUE TITLE
Definir o nome real do projeto

### ISSUE THREAD

**Issue by guilouro** [adote-um-fofinho/website#1]
Podemos colocar aqui algumas sugestões de nome para o projeto.

**Comment by mvfsilva** [comment]
Adote Um Amigo;

**Comment by JaderGJ** [comment]
Eu axo o título atual legal, então voto no [ Adote um fofinho ]

**Comment by willianjusten** [comment]
Eu curto a ideia do adote um fofinho, é um nome bastante "apelativo".
