### ISSUE TITLE
Layout do projeto

### ISSUE THREAD

**Issue by guilouro** [adote-um-fofinho/website#2]
- [ ]  Criação da logo. Podemos ter uma issue com um brainstorm somente sobre a logo
- [ ]  Crição da home. Podemos começar pela criação da página principal, para depois partir para as páginas internas.

**Comment by mvfsilva** [comment]
Boa Guilherme!

**Comment by guilouro** [comment]
Já temos alguém que dará inicio ao layout ?

**Comment by mvfsilva** [comment]
Adriano Tosta ?

**Comment by brunopulis** [comment]
@mvfsilva  já podia incluir desde a concepção do layout a acessibilidade.

**Comment by mvfsilva** [comment]
Com certeza @brunopulis, vamos conversar com o @adrianotosta

**Comment by adrianotosta** [comment]
Por enquanto vou apenas fazer uma pesquisa de similares e riscar um layout no photoshop, queria uma ferramenta de prototipagem free, mas nao encontrei nenhuma, voce conhece alguma @mvfsilva ????

**Comment by mvfsilva** [comment]
Galera já desenvolveram um projeto do mesmo tipo, querem dar continuidade  ?

**Comment by guilouro** [comment]
Qual é o link do projeto @mvfsilva ?

**Comment by mvfsilva** [comment]
@guilouro  segue: http://www.petch.com.br/

**Comment by adrianotosta** [comment]
imagina se o burguer king desistir de fazer hamburguer so por que o mc donald faz. imagina se a cacau show fecha so por que a kopenhagen ja faz. imagina se a apple desiste so porque a microsoft domina o mercado???!!! bullshit!!!! o importante nao é o que vc faz mas o COMO vc faz. Então pra mim o projeto continua licito.

**Comment by brunopulis** [comment]
Concordo com o @adrianotosta

**Comment by mvfsilva** [comment]
Então vamos nessa!

**Comment by brunopulis** [comment]
@mvfsilva  Até porque podemos explorar algo que o projeto do cara não tem e implementar no nosso! :)

**Comment by mvfsilva** [comment]
Beleza @brunopulis !

**Comment by guilouro** [comment]
Eu também concordo com o @adrianotosta !! Temos que ir adiante com o projeto

**Comment by mvfsilva** [comment]
@adrianotosta poderia fazer um layout para o projeto?
